on:
  push:
    branches: master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        run: composer install

      - name: Run Artisan commands
        run: |
          php artisan optimize
          php artisan migrate --force
          php artisan db:seed --force
        env:
          APP_ENV: production
          SENTRY_LARAVEL_DSN: ${{ secrets.SENTRY_LARAVEL_DSN }}
          DB_CONNECTION: sqlite
#          DB_CONNECTION: pgsql
#          DB_URL: ${{ secrets.DB_URL }}

      - name: Deploy to Vercel
        run: vercel deploy --force --prod --token=${{ secrets.VERCEL_LARACEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
